### ISSUE TITLE
Port must be a number

### ISSUE THREAD

**Issue by duypham90** [makbulut/laravel-aerospike#1]
Enviroment:

- Mac OS El capitan
- PHP 7.1
- Laravel: 5.5
- Latest Aerospike up to now

![screen shot 2018-02-23 at 8 40 03 am](https://user-images.githubusercontent.com/24804332/36573959-dee4f452-1875-11e8-8293-6342f239496d.png)

**Comment by makbulut** [comment]
Did you add following parameters to .env file ? Port number comes from .env and default is 3000 

AEROSPIKE_HOST=xxxxxx
AEROSPIKE_PORT=xxxxx
AEROSPIKE_NAMESPACE=xxxxx

**Comment by duypham90** [comment]
I have follow you guide
Here are errors:

.env
![screen shot 2018-02-26 at 8 32 31 am](https://user-images.githubusercontent.com/24804332/36649497-33c1b350-1ad0-11e8-9729-019b819c65d8.png)

Here is the result of config Hosts: Laravel auto convert all configs to string
![screen shot 2018-02-26 at 8 34 32 am](https://user-images.githubusercontent.com/24804332/36649512-43d6cdb6-1ad0-11e8-8e34-97bd96bd35a9.png)

Here is code I fixed this error.
![screen shot 2018-02-26 at 8 52 18 am](https://user-images.githubusercontent.com/24804332/36649834-97e4b236-1ad2-11e8-87c2-e31b26e2e75a.png)

The result: Port have already convert to number:
![screen shot 2018-02-26 at 8 35 35 am](https://user-images.githubusercontent.com/24804332/36649515-49a58e9e-1ad0-11e8-9ca2-7f274c57b0fc.png)

I fixed that by by modify code:

```php
<?php
/**
 * Created by PhpStorm.
 * User: makbulut
 * Date: 22/03/2017
 * Time: 07:28
 */

namespace Makbulut\Aerospike;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\ServiceProvider;

class AerospikeServiceProvider extends ServiceProvider
{

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
    }

    /**
     * Bootstrap the application events.
     *
     * @return void
     */
    public function boot()
    {
        $this->mergeConfigFrom(__DIR__ . '/../config/aerospike.php', 'cache.stores.aerospike');

        Cache::extend('aerospike', function ($app) {

            $config = $app['config'];

            $server = $config['cache.stores.aerospike.servers'];

            //convert port to number
            $server['hosts'] = array_map(function ($item) {
                $item['port'] = (int)$item['port'];
                return $item;
            }, $server['hosts']);

            $aerospike = new \Aerospike($server);

            $store = new AerospikeStore($aerospike, $config['cache.prefix'], $config['cache.stores.aerospike.namespace']);

            return Cache::repository($store);
        });
    }
}

```

**Comment by duypham90** [comment]
@makbulut 
https://www.aerospike.com/docs/client/php/install
Notice that I use the lastest php aerospike extension. Maybe you use old version.

**Comment by makbulut** [comment]
I see the problem, If we change the config file of my extension, it would be better. In config file, I got port with env function from .env file and env function returns it as string. 

```
'servers' => [
        "hosts" => [
            [
                "addr" => env('AEROSPIKE_HOST', 'localhost'),
                "port" => env('AEROSPIKE_PORT', 3000)
            ]
        ]
    ]
```

We can change it like following:
```
'servers' => [
        "hosts" => [
            [
                "addr" => env('AEROSPIKE_HOST', 'localhost'),
                "port" => (int) env('AEROSPIKE_PORT', 3000)
            ]
        ]
    ]
```

**Comment by hongduy1990** [comment]
@makbulut 
I have updated to 1.2 but it's still be string not integer
You should convert it in file AerospikeServiceProvider.php like me.

**Comment by duypham90** [comment]
Thank you.
