### ISSUE TITLE
Implement flush cache

### ISSUE THREAD

**Issue by nguyen-trung-mulodo** [makbulut/laravel-aerospike#3]
@makbulut : Can you implement method flush in class AerospikeStore
Here is my code
```php
public function flush()
{
    $this->aerospike->truncate($this->namespace, null, 0);
}
```
Reference: https://www.aerospike.com/apidocs/php/classes/Aerospike.html#method_truncate

**Comment by nguyen-trung-mulodo** [comment]
@makbulut

**Comment by nguyen-trung-mulodo** [comment]
@makbulut

**Comment by makbulut** [comment]
Sorry for delay, added that.

**Comment by nguyen-trung-mulodo** [comment]
Thank you so much!
